koths:
  koth1:
    name: "KOTH 1"
    world: "world"
    mode: "SCORE" # SCORE or CAPTURE
    corner1:
      x: 0
      y: 0
      z: 0
    corner2:
      x: 5
      y: 5
      z: 5
    kothTimes:
      - "10:00"
      - "2:00"
    commandsOnWin:
      - "say %player% has won"
      - "give %player% diamond 1"
    rules:
      maxTime: 5 # Time in seconds that koth will run for before timing out.
      pointsToWin: 100 # at a rate of 1 point per second
      winnerIfTimeRunsOut: true # the player with the most points/longest cap wins if the time runs out
    bossbar:
      enabled: true
      only-show-when-capturing: false
      # set to -1 to make it that everyone in the world can see it
      # set to 0 to make it that everyone on the server can see it
      view-distance: 64
      name: "#FF0000%name% #DDDDDD| #FF6600%currentCapturer% #DDDDDD(%timeLeft%)"
      # colors: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/boss/BarColor.html
      color: RED
      # styles: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/boss/BarStyle.html
      style: SEGMENTED_20
    scoreboard:
      enabled: true
      only-show-when-capturing: false
      # set to -1 to make it that everyone in the world can see it
      # set to 0 to make it that everyone on the server can see it
      view-distance: 64
      title: "#FF0000&l%name%"
      lines:
        - " "
        - "&cLocation:"
        - " &7| &fX%x%; Y%y%; Z%z%"
        - " "
        - "&cLeaderboard:"
        - " &e1. &f%scorePlayer1%: &f%scorePoints1%"
        - " &62. &f%scorePlayer2%: &f%scorePoints2%"
        - " &63. &f%scorePlayer3%: &f%scorePoints3%"
        - " &cYou: &f%score%"
        - " "
        - "&cEnds in:"
        - " &7❙ &f%timeLeft%"
        - " "
        - "&cplay.yourserver.com"
  koth2:
    name: "KOTH 2"
    world: "world"
    mode: "SCORE" # SCORE or CAPTURE
    corner1:
      x: 10
      y: 0
      z: 10
    corner2:
      x: 15
      y: 5
      z: 15
    kothTimes:
      - "11:00"
      - "3:00"
    commandsOnWin:
      - "say %player% has won %kothName%"
      - "give %player% diamond 1"
    rules:
      maxTime: 600 # Time in seconds that koth will run for before timing out.
      pointsToWin: 100 # at a rate of 1 point per second
      winnerIfTimeRunsOut: true # the player with the most points wins if the time runs out
    bossbar:
      enabled: true
      only-show-when-capturing: false
      # set to -1 to make it that everyone in the world can see it
      # set to 0 to make it that everyone on the server can see it
      view-distance: 64
      name: "#FF0000%name% #DDDDDD| #FF6600%currentCapturer% #DDDDDD(%timeLeft%)"
      # colors: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/boss/BarColor.html
      color: RED
      # styles: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/boss/BarStyle.html
      style: SEGMENTED_20
    scoreboard:
      enabled: true
      only-show-when-capturing: false
      # set to -1 to make it that everyone in the world can see it
      # set to 0 to make it that everyone on the server can see it
      view-distance: 64
      title: "#FF0000&l%name%"
      lines:
        - " "
        - "&cLocation:"
        - " &7| &fX%x%; Y%y%; Z%z%"
        - " "
        - "&cLeaderboard:"
        - " &e1. &f%scorePlayer1%: &f%scorePoints1%"
        - " &62. &f%scorePlayer2%: &f%scorePoints2%"
        - " &63. &f%scorePlayer3%: &f%scorePoints3%"
        - " &cYou: &f%score%"
        - " "
        - "&cEnds in:"
        - " &7❙ &f%timeLeft%"
        - " "
        - "&cplay.yourserver.com"