koths:
  koth_1:
    name: "KOTH 1"
    world: "world"
    corner1:
      x: 0
      y: 0
      z: 0
    corner2:
      x: 5
      y: 5
      z: 5
    kothTimes:
      - "10:00"
      - "2:00"
    commandsOnWin:
      - "say %player% has won"
      - "give %player% diamond 1"
    rules:
      maxTime: 600 # maximum time the koth can will run for
      pointsToWin: 100 # at a rate of 1 point per second
      winnerIfTimeRunsOut: true # the player with the most points wins if the time runs out
  koth_2:
    name: "KOTH 2"
    world: "world"
    corner1:
      x: 10
      y: 0
      z: 10
    corner2:
      x: 15
      y: 5
      z: 15
    kothTimes:
      - "11:00"
      - "3:00"
    commandsOnWin:
      - "say %player% has won %koth%"
      - "give %player% diamond 1"
    rules:
      maxTime: 600 # maximum time the koth can will run for
      pointsToWin: 100 # at a rate of 1 point per second
      winnerIfTimeRunsOut: true # the player with the most points wins if the time runs out